/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for dummy_chip
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <libraries/dummy_chip.h>

#include <interfaces/dummy_chip.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * dummy_chipBase = NULL;
static struct Library * __dummy_chipBase = NULL;

/****************************************************************************/

void dummy_chip_base_constructor(void)
{
    if (dummy_chipBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __dummy_chipBase = dummy_chipBase = IExec->OpenLibrary("dummy.chip", 0);
    if (dummy_chipBase == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to open 'dummy.chip'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzz"))) static void
(*dummy_chip_base_constructor_ptr)(void) USED = dummy_chip_base_constructor;

/****************************************************************************/

void dummy_chip_base_destructor(void)
{
    if (__dummy_chipBase != NULL)
    {
        IExec->CloseLibrary(__dummy_chipBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*dummy_chip_base_destructor_ptr)(void) USED = dummy_chip_base_destructor;

/****************************************************************************/

