/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for dummy_chip
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <libraries/dummy_chip.h>

#include <interfaces/dummy_chip.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

struct dummy_chipIFace * Idummy_chip = NULL;
static struct Library * __dummy_chipBase = NULL;
static struct dummy_chipIFace * __Idummy_chip = NULL;

/****************************************************************************/

extern struct Library * dummy_chipBase;

/****************************************************************************/

void dummy_chip_main_constructor(void)
{
    if (Idummy_chip != NULL)
    {
        return; /* Someone was quicker */
    }
    if (dummy_chipBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __dummy_chipBase = dummy_chipBase = IExec->OpenLibrary("dummy.chip", 0);
        if (dummy_chipBase == NULL)
        {
            IDOS->PutErrStr("ERROR: Failed to open 'dummy.chip'.\n");
            abort();
        }
    }

    __Idummy_chip = Idummy_chip = (struct dummy_chipIFace *)IExec->GetInterface((struct Library *)dummy_chipBase, "main", 1, NULL);
    if (Idummy_chip == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to get 'main' V1 interface for 'dummy.chip'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzy"))) static void
(*dummy_chip_main_constructor_ptr)(void) USED = dummy_chip_main_constructor;

/****************************************************************************/

void dummy_chip_main_destructor(void)
{
    if (__Idummy_chip)
    {
        IExec->DropInterface ((struct Interface *)__Idummy_chip);
    }
    if (__dummy_chipBase)
    {
        IExec->CloseLibrary(__dummy_chipBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*dummy_chip_main_destructor_ptr)(void) USED = dummy_chip_main_destructor;

/****************************************************************************/

