/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for dummy_card
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <libraries/dummy_card.h>

#include <interfaces/dummy_card.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * dummy_cardBase = NULL;
static struct Library * __dummy_cardBase = NULL;

/****************************************************************************/

void dummy_card_base_constructor(void)
{
    if (dummy_cardBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __dummy_cardBase = dummy_cardBase = IExec->OpenLibrary("dummy.card", 0);
    if (dummy_cardBase == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to open 'dummy.card'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzz"))) static void
(*dummy_card_base_constructor_ptr)(void) USED = dummy_card_base_constructor;

/****************************************************************************/

void dummy_card_base_destructor(void)
{
    if (__dummy_cardBase != NULL)
    {
        IExec->CloseLibrary(__dummy_cardBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*dummy_card_base_destructor_ptr)(void) USED = dummy_card_base_destructor;

/****************************************************************************/

