
/* This file was generated by idltool 53.24. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif
#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif
#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif
#ifndef LIBRARIES_DUMMY_CARD_H
#include <libraries/dummy_card.h>
#endif
#ifndef LIBRARIES_MAYBE_BOARDINFO_H
#include <libraries/maybe_boardinfo.h>
#endif

/* forward declaration */
struct DummycardIFace;

extern ULONG                VARARGS68K _dummy_card_Obtain(struct DummycardIFace *);
extern ULONG                VARARGS68K _dummy_card_Release(struct DummycardIFace *);
extern BOOL                 VARARGS68K _dummy_card_FindCard(struct DummycardIFace *, struct BoardInfo * bi);
extern void                 VARARGS68K _dummy_card_InitCard(struct DummycardIFace *, struct BoardInfo * bi, char ** ToolTypes);
extern BOOL                 VARARGS68K _dummy_card_InitChip(struct DummycardIFace *, struct BoardInfo * bi);
