
/* This file was generated by idltool 53.24. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif
#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif
#ifndef LIBRARIES_DUMMY_CHIP_H
#include <libraries/dummy_chip.h>
#endif

/* forward declaration */
struct dummy_chipIFace;

extern ULONG                VARARGS68K _dummy_chip_Obtain(struct dummy_chipIFace *);
extern ULONG                VARARGS68K _dummy_chip_Release(struct dummy_chipIFace *);
extern BOOL                 VARARGS68K _dummy_chip_FindCard(struct dummy_chipIFace *, struct boardinfo * bi);
extern void                 VARARGS68K _dummy_chip_InitCard(struct dummy_chipIFace *, struct boardinfo * bi, char ** ToolTypes);
extern BOOL                 VARARGS68K _dummy_chip_InitChip(struct dummy_chipIFace *, struct boardinfo * bi);
