
/* This file was generated by idltool 53.24. Do not edit */


/***************************************************************************/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif

#ifdef __NOGLOBALIFACE__
#undef __NOGLOBALIFACE__
#endif

#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif

#ifndef PROTO_DUMMY_CHIP_H
#include <proto/dummy_card.h>
#endif

#ifndef EXEC_EMULATION_H
#include <exec/emulation.h>
#endif

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif


#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif

#ifndef LIBRARIES_DUMMY_CHIP_H
#include <libraries/dummy_card.h>
#endif

/***************************************************************************/

