
/* This file was generated by idltool 53.24. Do not edit */

#include "dummy_chip_vectors.h"

STATIC uint32 VARARGS68K _dummy_chip_UNIMPLEMENTED(struct dummy_chipIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _dummy_chip_Obtain,
    _dummy_chip_Release,
    _dummy_chip_UNIMPLEMENTED, /* Expunge */
    _dummy_chip_UNIMPLEMENTED, /* Clone */
    _dummy_chip_FindCard,
    _dummy_chip_InitCard,
    _dummy_chip_InitChip,
    (APTR)-1
};
