#ifndef DUMMY.CHIP_INTERFACE_DEF_H
#define DUMMY.CHIP_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.24.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif
#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif
#ifndef LIBRARIES_DUMMY_CHIP_H
#include <libraries/dummy_chip.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct DummyChipIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct DummyChipIFace *Self);
	ULONG APICALL (*Release)(struct DummyChipIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	BOOL APICALL (*FindCard)(struct DummyChipIFace *Self, struct BoardInfo * bi);
	void APICALL (*InitCard)(struct DummyChipIFace *Self, struct BoardInfo * bi, char ** ToolTypes);
	BOOL APICALL (*InitChip)(struct DummyChipIFace *Self, struct BoardInfo * bi);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* DUMMY.CHIP_INTERFACE_DEF_H */
