#ifndef DUMMY_CARD_INTERFACE_DEF_H
#define DUMMY_CARD_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.24.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif
#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif
#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif
#ifndef LIBRARIES_DUMMY_CARD_H
#include <libraries/dummy_card.h>
#endif
#ifndef LIBRARIES_MAYBE_BOARDINFO_H
#include <libraries/maybe_boardinfo.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct DummycardIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct DummycardIFace *Self);
	ULONG APICALL (*Release)(struct DummycardIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	BOOL APICALL (*FindCard)(struct DummycardIFace *Self, struct BoardInfo * bi);
	void APICALL (*InitCard)(struct DummycardIFace *Self, struct BoardInfo * bi, char ** ToolTypes);
	BOOL APICALL (*InitChip)(struct DummycardIFace *Self, struct BoardInfo * bi);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* DUMMY_CARD_INTERFACE_DEF_H */
