
/* This file was generated by idltool 53.24. Do not edit */

#include "dummy_card_vectors.h"

STATIC uint32 VARARGS68K _dummy_card_UNIMPLEMENTED(struct DummycardIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _dummy_card_Obtain,
    _dummy_card_Release,
    _dummy_card_UNIMPLEMENTED, /* Expunge */
    _dummy_card_UNIMPLEMENTED, /* Clone */
    _dummy_card_FindCard,
    _dummy_card_InitCard,
    _dummy_card_InitChip,
    (APTR)-1
};
