#ifndef INLINE4_DUMMY_CHIP_H
#define INLINE4_DUMMY_CHIP_H

/*
** This file was auto generated by idltool 53.24.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef PROTO_EXEC_H
#include <proto/exec.h>
#endif
#ifndef PROTO_DOS_H
#include <proto/dos.h>
#endif
#ifndef LIBRARIES_DUMMY_CHIP_H
#include <libraries/dummy_chip.h>
#endif
#include <interfaces/dummy_chip.h>

/* Inline macros for Interface "main" */
#define FindCard(bi) Idummy_chip->FindCard((bi))
#define InitCard(bi, ToolTypes) Idummy_chip->InitCard((bi), (ToolTypes))
#define InitChip(bi) Idummy_chip->InitChip((bi))

#endif /* INLINE4_DUMMY_CHIP_H */
